name: 构建和发布(dev)

on:
  push:
    branches:
      - 'develop'

permissions:
  contents: write

jobs:
  build:
    if: ${{ github.event.head_commit && contains(github.event.head_commit.message, '(build)') }}
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
#restore
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      
      - name: Store
        uses: actions/cache@v4
        with:
          path: |
            ~/src-tauri/target
            ~/src-tauri/gen/android/.gradle
          key: ${{ runner.os }}-delta-comic-native
          restore-keys: |
            ${{ runner.os }}-delta-comic-native

      - name: Build script run pm
        run: chmod +x ./script/*
        
# rust
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android, armv7-linux-androideabi, i686-linux-android, x86_64-linux-android


# js
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.2.0
        with:
          version: 10.27.0

      - name: Use Node.js
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Change depends
        run: sh ./script/install.sh

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile


# java
      - name: JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: "gradle"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.2
        with:
          log-accepted-android-sdk-licenses: false

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.5.0
        id: setup-ndk
        with:
          ndk-version: r29
          link-to-sdk: true
          local-cache: true

      - name: Init android project
        run: |
          pnpm dlx @tauri-apps/cli android init

      - name: setup Android signing
        if: matrix.mobile == 'android'
        run: |
          cd src-tauri/gen/android
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" > keystore.properties
          echo "password=${{ secrets.ANDROID_KEY_PASSWORD }}" >> keystore.properties
          base64 -d <<< "${{ secrets.ANDROID_KEY_BASE64 }}" > $RUNNER_TEMP/keystore.jks
          echo "storeFile=$RUNNER_TEMP/keystore.jks" >> keystore.properties


# build
      - name: Build Android App
        id: build
        uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        with:
          mobile: "android"
          args: ""
          retryAttempts: 1
          prerelease: true
          tagName: "dev-v__VERSION__"
          releaseName: "dev build __VERSION__"
          releaseBody: |
            dev构建，不确保任何功能可以使用
            ${{ github.event.head_commit.message }}


#signature
      - name: Install apksigner
        run: sudo apt-get update && sudo apt-get install -y apksigner

      - name: Signature App
        run: |
          APK_SRC="./src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release-unsigned.apk"
          if [ -f "$APK_SRC" ]; then
            apksigner sign \
              --ks $RUNNER_TEMP/keystore.jks \
              --ks-key-alias ${{ secrets.ANDROID_KEY_ALIAS }} \
              --ks-pass pass:${{ secrets.ANDROID_KEY_PASSWORD }} \
              --key-pass pass:${{ secrets.ANDROID_KEY_PASSWORD }} \
              --v1-signing-enabled true \
              --v2-signing-enabled true \
              --v3-signing-enabled true \
              --out ./dist/app.apk \
              "$APK_SRC"
            echo '-----------'
            ls .
            echo '-----------'
            ls ./dist
          else
            echo "APK not found at $APK_SRC" >&2
            exit 1
          fi
                    

#publish
      - name: Release
        uses: softprops/action-gh-release@v2.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
           ./dist/app.apk
          tag_name: "dev-v${{ steps.build.outputs.appVersion }}"
          name: "Dev build v${{ steps.build.outputs.appVersion }}"
          body: |
            dev构建，不确保任何功能可以使用
            ${{ github.event.head_commit.message }}
          repository: ${{github.repository}}
          token: ${{ secrets.GITHUB_TOKEN }}
          make_latest: true
          prerelease: true