name: 各种检查
run-name: code-check

on:
  pull_request:
  push:
    branches: [main, develop]
    paths: '*.{js,jsx,ts,tsx,mts,cts,mjs,cjs,vue}'

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i --frozen-lockfile

      - name: lint
        run: |
          bun --bun exec oxlint --type-aware
          bun --bun exec oxfmt --check
          bun --bun exec cspell --no-exit-code